server:
  port: 8080
jwt:
  expiration: 36000
  secret: secret

spring:
  jpa:
    hibernate:
      ddl-auto: update

  data:
    jpa.repositories.enabled: true
  datasource:
    initialization-mode: always
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/app2
    username: postgres
    password: lalo
    continueOnError: true